server:
  port: 8084

spring:
  application:
    name: mall-risk-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://100.121.74.115:3306/db_risk?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
    hikari:
      maximum-pool-size: 20
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:100.121.74.115:8848}
      config:
        server-addr: ${NACOS_SERVER_ADDR:100.121.74.115:8848}

rocketmq:
  name-server: 100.120.228.17:9876
  producer:
    group: risk-command-producer-group

risk:
  identity-salt: change-me-in-production
  precheck-expire-minutes: 10

dubbo:
  application:
    name: mall-risk-service
    register-mode: interface
  registry:
    address: nacos://100.121.74.115:8848/
  protocol:
    name: dubbo
    port: 20884
  scan:
    base-packages: com.example.risk.provider
xxl:
  job:
    admin:
      addresses: ${XXL_JOB_ADMIN_ADDRESSES:http://100.121.74.115:8090/xxl-job-admin}
    executor:
      appname: ${XXL_JOB_EXECUTOR_APPNAME:mall-risk-executor}
      port: ${XXL_JOB_EXECUTOR_PORT:9998}
      logpath: ${XXL_JOB_LOG_PATH:./logs/xxl-job/jobhandler}
      logretentiondays: ${XXL_JOB_LOG_RETENTION_DAYS:30}
    accessToken: ${XXL_JOB_ACCESS_TOKEN:default_token}
